[package]
name = "spiderweb"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = "2.5.0"
bytes = "1.12.1"
local-ip-address = "0.6.13"
mdns-sd = { version = "0.21.0" }
rkyv = "0.8.18"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "net", "sync", "io-util"] }
